export { default as compact } from './obbie/compact'
export { default as deleteIf } from './obbie/deleteIf'
export { default as dig } from './obbie/dig'
export { default as fetch } from './obbie/fetch'
export { default as length } from './obbie/length'
